SEED_KEYWORDS = [
    # --- Backcountry Hunting & Upland Birds ---
    "backcountry elk hunting tips",
    "public land elk hunting strategy",
    "elk hunting boots review",
    "backcountry hunting pack comparison",
    "high country mule deer hunting",
    "backcountry deer hunting gear list",
    "upland bird hunting dogs",
    "pheasant hunting vest",
    "grouse hunting tips",
    "chukar hunting gear",
    "upland hunting boots for rough terrain",
    "backcountry hunting binoculars",
    "elk calling techniques",
    "solo backcountry elk hunt",
    "meat pack out system hunting",
    "backcountry hunting food list",
    "bear canister hunting use",
    "archery elk hunting tips",
    "backcountry hunting rifle selection",
    "upland bird hunting colorado",

    # --- Backpacking & Hiking Gear ---
    "ultralight backpacking gear list",
    "best backpacking tent under 2 lbs",
    "backpacking sleeping bag temperature rating",
    "trekking poles for backpacking",
    "trail running shoes for backpacking",
    "backpacking stove comparison",
    "water filter for backpacking",
    "backpacking food ideas",
    "daypack vs backpacking pack",
    "best hiking socks for blisters",
    "base layer for hiking",
    "rain jacket hiking review",
    "thru hiking gear checklist",
    "long distance hiking training plan",
    "hiking pole tips replacement",
    "waterproof hiking boots vs trail runners",
    "backpacking bear bag system",
    "trekking pole vs hiking staff",
    "best budget backpacking gear",
    "backpacking first aid kit essentials",

    # --- Camping Planning & Permits ---
    "recreation.gov permit tips",
    "how to get camping permits",
    "dispersed camping rules national forest",
    "free camping near national parks",
    "camping reservation system recreation gov",
    "walk up camping permit strategy",
    "lottery camping permits guide",
    "car camping checklist beginners",
    "camping meal planning for a week",
    "campfire regulations western states",
    "leave no trace camping principles",
    "camping near popular trailheads",
    "camping permit release dates 2025",
    "camping without reservation options",
    "best campsites colorado reservations",
    "camping reservation cancellation tips",
    "national forest camping permit application",
    "primitive camping gear list",
    "group camping permit process",
    "camping in bear country food storage",

    # --- Overlanding ---
    "overlanding vehicle setup guide",
    "overland camping gear list",
    "best overlanding roof tent",
    "overlanding recovery gear essentials",
    "4x4 overlanding trail tips",
    "overlanding solar setup",
    "overlanding fridge review",
    "overlanding water storage solutions",
    "truck bed overlanding setup",
    "overlanding communication devices",
    "overlanding colorado trails",
    "overland expedition packing list",
    "overlanding air compressor review",
    "best overlanding truck accessories",
    "overlanding winch selection guide",
    "overlanding cooking setup",
    "weekend overlanding trip planning",
    "overlanding suspension upgrades",
    "high clearance overlanding routes",
    "overlanding tool kit essentials",

    # --- Fly Fishing Gear ---
    "fly fishing rod for beginners",
    "best fly fishing reel under 200",
    "dry fly vs nymph fishing techniques",
    "fly fishing waders review",
    "fly fishing boots with studs",
    "best fly line for trout",
    "fly fishing leader and tippet setup",
    "fly fishing net review",
    "small stream fly fishing tips",
    "fly fishing vest vs pack",
    "fly tying materials for beginners",
    "euro nymphing setup guide",
    "fly fishing colorado rivers",
    "streamer fishing techniques for trout",
    "fly fishing polarized sunglasses",
    "best fly fishing pack",
    "fly fishing indicator nymphing",
    "fly rod weight selection guide",
    "fly fishing license colorado",
    "high altitude fly fishing tips",

    # --- Colorado / Western Outdoor Recreation ---
    "best hikes in colorado 14ers",
    "colorado 14er permit requirements",
    "colorado backpacking trips beginners",
    "best fly fishing rivers in colorado",
    "colorado hunting license application",
    "dispersed camping colorado national forest",
    "colorado river rafting permits",
    "best ski touring routes colorado",
    "colorado trail through hike guide",
    "colorado mountain biking trails",
    "best wildlife viewing in colorado",
    "colorado elk hunting units map",
    "colorado camping reservations state parks",
    "rocky mountain national park day hike permit",
    "colorado gold medal fishing waters",
    "colorado winter camping tips",
    "best overlanding routes colorado",
    "colorado wilderness permit areas",
    "colorado backcountry skiing tips",
    "colorado outdoor recreation license application",
]
